# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ParticleSampleApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ParticleSampleApp
  pod 'Particle-SDK'
  pod 'ParticleSetup'

  target 'ParticleSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ParticleSampleApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ParticleSampleApp-tvOS

  target 'ParticleSampleApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
